import { ReportsRepository } from '../repository/reports.repository.js';
import { ProviderFactory } from '../../ai/provider/provider.factory.js';
import { prisma } from '../../../config/prisma.js';
import { AppError } from '../../../utils/AppError.js';
import { sendReportEmail } from '../../../utils/mailer.js';
import fs from 'fs';
import path from 'path';

const reportsRepo = new ReportsRepository();

export class ReportsService {
  private getStorageDir() {
    const dir = path.join(process.cwd(), 'uploads', 'reports');
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    return dir;
  }

  public async getReports(userId: string) {
    return reportsRepo.getReports(userId);
  }

  public async getReportById(userId: string, id: string) {
    const report = await reportsRepo.getReportById(userId, id);
    if (!report) {
      throw new AppError('Report not found', 404);
    }
    return report;
  }

  public async generateReport(userId: string, type: string, month: number, year: number, generatedBy = 'USER') {
    // 1. Fetch financial data
    const [accounts, budgets, goals, transactions, user] = await Promise.all([
      prisma.account.findMany({ where: { userId, isArchived: false } }),
      prisma.budget.findMany({ where: { userId }, include: { category: true } }),
      prisma.goal.findMany({ where: { userId } }),
      prisma.transaction.findMany({ where: { userId }, include: { category: true, account: true } }),
      prisma.user.findUnique({ where: { id: userId }, include: { preferences: true } }),
    ]);

    if (!user) {
      throw new AppError('User not found', 404);
    }

    const netWorth = accounts.reduce((sum, a) => sum + a.balance, 0);
    const monthlyTx = transactions.filter(t => {
      const d = new Date(t.date);
      return d.getMonth() + 1 === month && d.getFullYear() === year;
    });

    const totalIncome = monthlyTx.filter(t => t.type === 'INCOME').reduce((sum, t) => sum + t.amount, 0);
    const totalExpenses = monthlyTx.filter(t => t.type === 'EXPENSE').reduce((sum, t) => sum + t.amount, 0);
    const savings = totalIncome - totalExpenses;

    // Category Spending Breakdown
    const catMap: Record<string, number> = {};
    monthlyTx.filter(t => t.type === 'EXPENSE').forEach(t => {
      const name = t.category?.name || 'Uncategorized';
      catMap[name] = (catMap[name] || 0) + t.amount;
    });

    const highestSpendingCat = Object.keys(catMap).length > 0 
      ? Object.entries(catMap).reduce((a, b) => a[1] > b[1] ? a : b)[0]
      : 'None';

    // 2. Generate AI summary
    let aiSummary = 'No AI Summary generated.';
    try {
      const provider = ProviderFactory.getProvider();
      const prompt = `You are a professional Financial Advisor. Below is the monthly financial statement for ${user.fullName} for ${month}/${year}.
- Net Worth: INR ${netWorth}
- Total Income: INR ${totalIncome}
- Total Expenses: INR ${totalExpenses}
- Net Savings: INR ${savings}
- Highest Spending Category: ${highestSpendingCat}
- Budgets: ${budgets.map(b => `${b.category?.name}: Limit INR ${b.amount}`).join(', ')}
- Savings Goals: ${goals.map(g => `${g.name}: Target INR ${g.targetAmount}, Saved INR ${g.currentAmount}`).join(', ')}

Please provide:
1. A concise, warm, professional executive summary of the month.
2. 3 concrete spending insights and savings opportunities.
3. 2 action items for next month.
Keep it strictly under 300 words. Format with markdown bolding and bullet points.`;

      const aiResponse = await provider.chat({
        messages: [{ role: 'user', content: prompt }],
        systemPrompt: 'You are a warm, professional financial coach.',
      });
      aiSummary = aiResponse.content || aiSummary;
    } catch (err) {
      console.warn('AI summary generation failed, using fallback.', err);
    }

    // 3. Formulate report file content based on type/format
    const reportData = {
      user: user.fullName,
      month,
      year,
      summary: {
        netWorth,
        totalIncome,
        totalExpenses,
        savings,
        highestSpendingCat,
      },
      aiSummary,
      budgets: budgets.map(b => ({ category: b.category?.name, limit: b.amount })),
      goals: goals.map(g => ({ name: g.name, target: g.targetAmount, current: g.currentAmount })),
    };

    const fileName = `Financial_Report_${month}_${year}_${Date.now()}.txt`;
    const storagePath = path.join(this.getStorageDir(), fileName);

    // Save formatted text/markdown version of the report
    const fileContent = `==================================================
FINANCIAL REPORT - ${month}/${year}
==================================================
Generated By: ${generatedBy}
Generated At: ${new Date().toLocaleString()}

FINANCIAL SUMMARY:
- Total Income: INR ${totalIncome}
- Total Expenses: INR ${totalExpenses}
- Net Savings: INR ${savings}
- Net Worth: INR ${netWorth}

CATEGORY SPENDING BREAKDOWN:
${Object.entries(catMap).map(([cat, amt]) => `- ${cat}: INR ${amt}`).join('\n') || 'No spending recorded.'}

BUDGET PERFORMANCE:
${budgets.map(b => `- ${b.category?.name}: Limit INR ${b.amount}`).join('\n') || 'No budgets configured.'}

SAVINGS GOALS PROGRESS:
${goals.map(g => `- ${g.name}: Target INR ${g.targetAmount} | Saved: INR ${g.currentAmount}`).join('\n') || 'No goals created.'}

==================================================
AI FINANCIAL COACH ADVICE & INSIGHTS:
==================================================
${aiSummary}
==================================================`;

    fs.writeFileSync(storagePath, fileContent, 'utf-8');

    // 4. Save to Database
    const report = await reportsRepo.createReport({
      userId,
      type,
      month,
      year,
      fileName,
      format: 'PDF',
      storagePath,
      generatedBy,
    });

    return report;
  }

  public async getReportFile(userId: string, id: string) {
    const report = await this.getReportById(userId, id);
    if (!fs.existsSync(report.storagePath)) {
      throw new AppError('Physical report file not found on disk', 404);
    }
    return {
      fileName: report.fileName,
      content: fs.readFileSync(report.storagePath, 'utf-8'),
    };
  }

  public async emailReport(userId: string, id: string) {
    const report = await this.getReportById(userId, id);
    const user = await prisma.user.findUnique({
      where: { id: userId },
      include: { preferences: true },
    });

    if (!user) {
      throw new AppError('User not found', 404);
    }

    const email = user.preferences?.monthlyReportEmail || user.email;
    const fileData = await this.getReportFile(userId, id);

    const subject = `Your Monthly Financial Report - ${report.month}/${report.year}`;
    const htmlContent = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 12px;">
        <h2 style="color: #111; margin-bottom: 16px;">FinTrack Report</h2>
        <p style="color: #374151; font-size: 16px;">Hello ${user.fullName},</p>
        <p style="color: #374151; font-size: 14px; line-height: 1.5;">
          Your monthly financial statement for <strong>${report.month}/${report.year}</strong> has been generated successfully.
        </p>
        <p style="color: #374151; font-size: 14px; line-height: 1.5;">
          We have attached the detailed summary report to this email.
        </p>
        <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <p style="color: #6b7280; font-size: 12px;">FinTrack Personal Finance Manager.</p>
      </div>
    `;

    await sendReportEmail(email, subject, htmlContent, fileData.fileName, fileData.content);

    await reportsRepo.updateReport(id, {
      emailed: true,
      emailedAt: new Date(),
    });

    return { success: true, emailedTo: email };
  }

  public async deleteReport(userId: string, id: string) {
    const report = await reportsRepo.getReportById(userId, id);
    if (report) {
      if (fs.existsSync(report.storagePath)) {
        fs.unlinkSync(report.storagePath);
      }
      await reportsRepo.deleteReport(userId, id);
    }
    return { success: true };
  }
}
export default ReportsService;
