version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: finance-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_DB: finance_manager

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: